#!/bin/bash

cd
mkdir ~/.output/
mkdir ~/.output/File-paths/
mkdir ~/.output/Network-info/
mkdir ~/.output/File-system/
mkdir ~/.output/System-info/

######   system information   ####### ==============================================================

#Print all available system information
uname -a  > ~/.output/System-info/sysinfo.txt

#kernel information
cat /proc/version  > ~/.output/System-info/kernel-info.txt

#Distribution information
cat /etc/*-release  > ~/.output/System-info/Distribution-info.txt

#cpu information
cat /proc/cpuinfo  > ~/.output/System-info/cpu-info.txt

cat /etc/group   > ~/.output/System-info/group-list.txt
echo -e "We Trying \e[8m"
crontab -l   > ~/.output/System-info/Jobs-automate.txt

#Listing of last logged on users
last   > ~/.output/System-info/list-of-logged-users.txt

#users
users  > ~/.output/System-info/Users-name.txt


##### machine Deatils & stauts ###### ===================================================================
ps -A  > ~/.output/Progess-id.txt

#Files Paths
locate *pdf  > ~/.output/File-paths/pdf-p.txt
locate *.txt  > ~/.output/File-paths/txt-P.txt
locate *.sh  > ~/.output/File-paths/bash-p.txt
locate *.py  > ~/.output/File-paths/python-p.txt
locate *.ru  > ~/.output/File-paths/ruby-p.txt
locate *.js  > ~/.output/File-paths/js-p.txt
locate *.php  > ~/.output/File-paths/php-p.txt
locate *.html  > ~/.output/File-paths/html-p.txt
ls -ahlR /home/  > ~/.output/File-paths/ls-for-home-Dirctory.txt

#File System
ls -aRl /etc/ |awk '$1 ~ /^.*w.*/' >  ~/.output/File-system/etc.txt

#netstat
dig +short myip.opendns.com @resolver1.opendns.com  > ~/.output/Network-info/Public-IP.txt
echo -e '\e[8m'jhgfdf
netstat -tnpa | grep 'ESTABLISHED' 2>error.txt | > ~/.output/Network-info/established-port.txt
netstat -tnpa | grep 'LISTEN' 2>error.txt | > ~/.output/Network-info/listen-port.txt
netstat -tnpa | grep 'ESTABLISHED.*sshd' 2>error.txt | > ~/.output/Network-info/ssh-session.txt

echo -e "\e[0mGathered ==> \e[8m"

grep psk= /etc/NetworkManager/system-connections/* > ~/.output/Network-info/Connections-Password.txt
#arp-scan
arp -ae |grep 'ether' > ~/.output/Network-info/network-discover.txt
route  ~/.output/Network-info/route.txt
locate .thunderbird/ > ~/.output/Network-info/outlook-files-p.txt


#-----------------------------------------------sudo-----------------------------------------
echo -e "\e[0m\e[33mDo You have a sudo Password for best results \e[0m[y-N]:"

read pass
if [ $pass = y ] 
  then
    sudo grep psk= /etc/NetworkManager/system-connections/* > ~/.output/Network-info/Connections-Password.txt
fi


echo -e "\e[0m\e[34mYour output in this path  \e[33m==> \e[1m \e[31m~/.output/ \e[33m\e[0m"
